cache:
  - c:\cargo\registry
  - c:\cargo\git

init:
  - mkdir c:\cargo
  - mkdir c:\rustup
  - SET PATH=c:\cargo\bin;%PATH%

clone_folder: c:\projects\intspan

environment:
  CARGO_HOME: "c:\\cargo"
  RUSTUP_HOME: "c:\\rustup"
  CARGO_TARGET_DIR: "c:\\projects\\intspan\\target"
  global:
    PROJECT_NAME: intspan
    RUST_BACKTRACE: full
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
      BITS: 64
      MSYS2: 1
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
      BITS: 64
    - TARGET: i686-pc-windows-gnu
      CHANNEL: stable
      BITS: 32
      MSYS2: 1
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
      BITS: 32

matrix:
  fast_finish: true

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustc -V
  - cargo -V

# Hack to work around a harmless warning in Appveyor builds?
build: false

# Equivalent to Travis' `script` phase
test_script:
  - cargo test --verbose --all -- --test-threads=1

branches:
  only:
    - /^\d+\.\d+\.\d+$/
    - master
