name: Code Coverage

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: codecov
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --bins --tests --follow-exec --engine llvm --out xml -- --test-threads 1

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{secrets.CODECOV_TOKEN}}
