name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  linux-gnu:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: actions/checkout@v1
      - name: Enable Link Time Optimizations
        run: |
          echo "[profile.release]" >> Cargo.toml
          echo "lto = true" >> Cargo.toml
      - name: Build
        run: cargo build --verbose --release
      - name: Create tarball
        run: tar cvfz intspan.tar.gz target/release/spanr target/release/linkr target/release/ovlpr
        shell: bash
      - name: Upload binaries to releases
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: intspan.tar.gz
          asset_name: intspan-x86_64-unknown-linux-gnu.tar.gz
          tag: ${{ github.ref }}
  macos:
    runs-on: macOS-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: actions/checkout@v1
      - name: Enable Link Time Optimizations
        run: |
          echo "[profile.release]" >> Cargo.toml
          echo "lto = true" >> Cargo.toml
      - name: Build
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.12
        run: cargo build --verbose --release
      - name: Create tarball
        run: tar cvfz intspan.tar.gz target/release/spanr target/release/linkr target/release/ovlpr
        shell: bash
      - name: Upload binaries to releases
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: intspan.tar.gz
          asset_name: intspan-x86_64-apple-darwin.tar.gz
          tag: ${{ github.ref }}
  windows:
    runs-on: windows-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: actions/checkout@v1
      - name: Enable Link Time Optimizations
        run: |
          echo "[profile.release]" >> Cargo.toml
          echo "lto = true" >> Cargo.toml
      - name: Enable static CRT linkage
        run: |
          mkdir .cargo
          echo '[target.x86_64-pc-windows-msvc]' >> .cargo/config
          echo 'rustflags = ["-Ctarget-feature=+crt-static"]' >> .cargo/config
      - name: Build
        run: cargo build --verbose --release
      - name: Create zip
        with:
          args: Compress-Archive -DestinationPath ./intspan.zip -Path ./target/release/spanr,./target/release/linkr,./target/release/ovlpr
        shell: powershell
      - name: Upload binaries to releases
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: intspan.zip
          asset_name: intspan-x86_64-pc-windows-msvc.zip
          tag: ${{ github.ref }}

#TODO: https://github.com/hecrj/iced/blob/master/.github/workflows/build.yml
#  x86_64-unknown-linux-musl
